// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksgfhjpxkubxkuylxdgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZ2ZoanB4a3VieGt1eWx4ZGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjMzNTAsImV4cCI6MjA2NDMzOTM1MH0.mnpbCrT-_5CSShqdgxD-UiN5BAyh_-g-7sxJbHQydBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);